import React from "react";
import { useEffect, useState } from 'react';
import { api, getCurrentUser } from '../services/api.js';

export default function Appointments(){
 const user=getCurrentUser(); const [appointments,setAppointments]=useState([]); const [doctors,setDoctors]=useState([]); const [patients,setPatients]=useState([]); const [error,setError]=useState('');
 const [form,setForm]=useState({patient:'',doctor:'',date:'',time:'',reason:'',department:''});
 const load=async()=>{try{setAppointments(await api.appointments()); setDoctors(await api.doctors()); if(user.role==='admin') setPatients(await api.patients());}catch(e){setError(e.message)}}; useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const add=async(e)=>{e.preventDefault(); try{const payload={...form}; if(user.role==='patient') delete payload.patient; await api.createAppointment(payload); setForm({patient:'',doctor:'',date:'',time:'',reason:'',department:''}); load();}catch(err){setError(err.message)}};
 const update=async(id,status)=>{await api.updateAppointment(id,{status}); load();};
 return <section className="page"><div className="page-head"><div><p className="eyebrow">Appointments</p><h1>Appointment Management</h1></div></div>{error&&<div className="error-box">{error}</div>}{user.role!=='doctor'&&<form className="content-card form-card" onSubmit={add}><div className="card-head"><h2>Book Appointment</h2></div><div className="form-grid">{user.role==='admin'&&<select className="plain-input" name="patient" required value={form.patient} onChange={change}><option value="">Select Patient</option>{patients.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select>}<select className="plain-input" name="doctor" required value={form.doctor} onChange={change}><option value="">Select Doctor</option>{doctors.map(d=><option key={d._id} value={d._id}>{d.name} - {d.specialization}</option>)}</select><input className="plain-input" name="date" type="date" required value={form.date} onChange={change}/><input className="plain-input" name="time" type="time" required value={form.time} onChange={change}/><input className="plain-input" name="department" placeholder="Department" value={form.department} onChange={change}/><input className="plain-input" name="reason" placeholder="Reason" required value={form.reason} onChange={change}/></div><button className="primary-btn">Book Appointment</button></form>}<div className="content-card"><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Doctor</th><th>Date</th><th>Time</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>{appointments.map(a=><tr key={a._id}><td><b>{a.patient?.name}</b></td><td>{a.doctor?.name}</td><td>{a.date}</td><td>{a.time}</td><td>{a.reason}</td><td><span className={`badge ${a.status?.toLowerCase()}`}>{a.status}</span></td><td>{(user.role==='admin'||user.role==='doctor')&&<div className="row-actions"><button onClick={()=>update(a._id,'Approved')}>Approve</button><button onClick={()=>update(a._id,'Completed')}>Complete</button><button onClick={()=>update(a._id,'Cancelled')}>Cancel</button></div>}</td></tr>)}</tbody></table></div></div></section>
}
