import React from "react";
import { useEffect, useState } from 'react';
import { api, getCurrentUser } from '../services/api.js';

export default function Prescriptions(){
 const user=getCurrentUser(); const [prescriptions,setPrescriptions]=useState([]); const [appointments,setAppointments]=useState([]); const [error,setError]=useState('');
 const [form,setForm]=useState({appointment:'',patient:'',doctor:'',symptoms:'',diagnosis:'',medicineName:'',dosage:'',duration:'',advice:'',followUpDate:''});
 const load=async()=>{try{setPrescriptions(await api.prescriptions()); setAppointments(await api.appointments());}catch(e){setError(e.message)}}; useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const selectAppointment=(id)=>{const a=appointments.find(x=>x._id===id); setForm({...form, appointment:id, patient:a?.patient?._id||'', doctor:a?.doctor?._id||''});};
 const add=async(e)=>{e.preventDefault(); try{await api.createPrescription({appointment:form.appointment||undefined, patient:form.patient, doctor:form.doctor, symptoms:form.symptoms, diagnosis:form.diagnosis, advice:form.advice, followUpDate:form.followUpDate, medicines:[{name:form.medicineName,dosage:form.dosage,duration:form.duration}]}); setForm({appointment:'',patient:'',doctor:'',symptoms:'',diagnosis:'',medicineName:'',dosage:'',duration:'',advice:'',followUpDate:''}); load();}catch(err){setError(err.message)}};
 return <section className="page"><div className="page-head"><div><p className="eyebrow">Prescriptions</p><h1>Prescription Management</h1></div></div>{error&&<div className="error-box">{error}</div>}{(user.role==='admin'||user.role==='doctor')&&<form className="content-card form-card" onSubmit={add}><div className="card-head"><h2>Add Prescription</h2></div><div className="form-grid"><select className="plain-input" value={form.appointment} onChange={(e)=>selectAppointment(e.target.value)}><option value="">Select Appointment</option>{appointments.map(a=><option key={a._id} value={a._id}>{a.patient?.name} - {a.date} - {a.time}</option>)}</select><input className="plain-input" name="symptoms" placeholder="Symptoms" value={form.symptoms} onChange={change}/><input className="plain-input" name="diagnosis" required placeholder="Diagnosis" value={form.diagnosis} onChange={change}/><input className="plain-input" name="medicineName" required placeholder="Medicine name" value={form.medicineName} onChange={change}/><input className="plain-input" name="dosage" placeholder="Dosage" value={form.dosage} onChange={change}/><input className="plain-input" name="duration" placeholder="Duration" value={form.duration} onChange={change}/><input className="plain-input" name="followUpDate" type="date" value={form.followUpDate} onChange={change}/><input className="plain-input" name="advice" placeholder="Advice" value={form.advice} onChange={change}/></div><button className="primary-btn">Save Prescription</button></form>}<div className="cards-grid">{prescriptions.map(p=><div className="content-card" key={p._id}><div className="card-head"><h2>{p.patient?.name}</h2><span>{p.createdAt?.slice(0,10)}</span></div><p><b>Doctor:</b> {p.doctor?.name}</p><p><b>Diagnosis:</b> {p.diagnosis}</p><p><b>Symptoms:</b> {p.symptoms || '-'}</p><p><b>Medicines:</b> {p.medicines?.map(m=>`${m.name} ${m.dosage} ${m.duration}`).join(', ')}</p><p><b>Advice:</b> {p.advice || '-'}</p></div>)}</div></section>
}
